version: '3'
services:
  app:
    restart: always
    volumes:
      - ./app:/app
    build: .
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
    command: ["gunicorn", "--config", "/app/gunicorn-cfg.py", "application:application"]

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge